services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 15s
      timeout: 5s
      retries: 5
  
  mysql_usuarios:
    image: mysql:latest
    container_name: contenedor_mysql_usuarios
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p admin123"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./ServicioUsuarios/database/usuarios_bd_assignu.sql:/docker-entrypoint-initdb.d/usuarios_db_assignu.sql
      - volumen_mysql_usuarios:/var/lib/mysql
    ports:
      - "3307:3306"
  
  mysql_clases:
    image: mysql:latest
    container_name: contenedor_mysql_clases
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p admin123"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./ServicioClases/database/clases_bd_assignu.sql:/docker-entrypoint-initdb.d/clases_db_assignu.sql
      - volumen_mysql_clases:/var/lib/mysql
    ports:
      - "3308:3306"
  
  mysql_tareas:
    image: mysql:latest
    container_name: contenedor_mysql_tareas
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p admin123"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./ServicioTareas/database/tareas_bd_assignu.sql:/docker-entrypoint-initdb.d/tareas_db_assignu.sql
      - volumen_mysql_tareas:/var/lib/mysql
    ports:
      - "3309:3306"
  
  mongo_cuestionarios:
    image: mongodb/mongodb-community-server:7.0.21-rc0-ubi8
    container_name: contenedor_mongodb_cuestionarios
    ports:
      - "27017:27017"
    volumes:
      - volumen_mongo_cuestionarios:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  mongo_archivos:
    image: mongodb/mongodb-community-server:7.0.21-rc0-ubi8
    container_name: contenedor_mongodb_archivos
    ports:
      - "27018:27017"
    volumes:
      - volumen_mongo_archivos:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  servicio_usuarios:
    image: imagen_servicio_usuarios:1.0
    depends_on:    
      rabbitmq:
        condition: service_healthy
      mysql_usuarios:
        condition: service_healthy
    ports:
      - "5001:80"
  
  servicio_clases:
    image: imagen_servicio_clases:1.0
    depends_on:    
      rabbitmq:
        condition: service_healthy
      mysql_clases:
        condition: service_healthy
    ports:
      - "5002:80"
  
  servicio_tareas:
    image: imagen_servicio_tareas:1.0
    depends_on:    
      rabbitmq:
        condition: service_healthy
      mysql_tareas:
        condition: service_healthy
    ports:
      - "5003:80"
  
  servicio_cuestionarios:
    image: imagen_servicio_cuestionarios:1.0
    depends_on:    
      rabbitmq:
        condition: service_healthy
      mongo_cuestionarios:
        condition: service_healthy
    ports:
      - "5004:80"

  servicio_archivos:
    image: imagen_servicio_archivos:1.0
    depends_on:    
      rabbitmq:
        condition: service_healthy
      mongo_archivos:
        condition: service_healthy
    ports:
      - "5005:5005"

  apigateway:
    image: imagen_apigateway:1.0
    ports:
      - "5010:5010"
      - "5011:5011"
    depends_on:
      - servicio_usuarios
      - servicio_clases
      - servicio_tareas
      - servicio_cuestionarios
      - servicio_archivos

volumes:
  volumen_mysql_usuarios:
  volumen_mysql_clases:
  volumen_mysql_tareas:
  volumen_mongo_cuestionarios:
  volumen_mongo_archivos: